# Generated by Django 2.0 on 2022-11-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_voting_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='visibility',
            field=models.BooleanField(),
        ),
    ]
