# Generated by Django 2.0 on 2022-11-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20221122_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='visibility',
            field=models.NullBooleanField(),
        ),
    ]
