# Generated by Django 2.0 on 2022-11-24 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20221124_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voting',
            old_name='visibility',
            new_name='public',
        ),
    ]
