# Generated by Django 2.0 on 2022-11-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'managed': False},
        ),
    ]
