# Generated by Django 2.0 on 2022-11-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20221123_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={},
        ),
    ]
