# Generated by Django 2.0 on 2022-12-02 01:15

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20221124_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='country',
            field=django_countries.fields.CountryField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
